### PR TITLE
4 when loading multi year data add a spinner while years are loaded

### PR DESCRIPTION
**Pull request by sowdm**
This pull request should be handled after the Multi-Year pull request

### CODE REVIEW

**Review by potto216 — APPROVED** [review]
Looks good, but not able to see the spinner when loading MULTI for Arizona  or California agencies that had MULTI years. I guess they loaded to fast.

Like switch to logging statements.

**Comment by potto216** [comment]
@sowdm did you want to resolve the conflicts?

**Comment by sowdm** [comment]
> @sowdm did you want to resolve the conflicts?

Yeah, I will handle the merge

**Comment by sowdm** [comment]
> Looks good, but not able to see the spinner when loading MULTI for Arizona or California agencies that had MULTI years. I guess they loaded to fast.
> 
> Like switch to logging statements.

Yeah, it is usually quite fast. Probably still good to have it in case it ever isn't

**Pull request merged**
